### ISSUE TITLE
The module teaches use of deprecated functions from SciPy

### ISSUE THREAD

**Issue by ThomasA** [arokem/scipy-optimize#5]
The functions `mlab.csv2rec` and `mlab.rec2csv` are [deprecated as of Matplotlib v. 2.2](https://matplotlib.org/api/mlab_api.html#matplotlib.mlab.csv2rec). Perhaps a replacement method should be considered in order not to teach methods that are going to disappear from the tools we use?

**Comment by arokem** [comment]
Thanks for pointing this out. 

I now use Pandas instead, implemented in https://github.com/arokem/scipy-optimize/commit/873917ae4a48207a606b3f7759e845ae3f4c3019
